// FRONTREACT/front-react/src/components/admin-visages/AdminVisages.tsx
import React, { useState, useEffect } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { serveurService } from '../../services/serveur.service';
import { apiFetch } from '../../services/jwt.interceptor';

export const AdminVisages: React.FC = () => {
  const navigate = useNavigate();
  const [visages, setVisages] = useState<any[]>([]);
  const [imageZoomee, setImageZoomee] = useState<number | null>(null);

  // 👉 Nouveaux états pour les filtres
  const [filtreId, setFiltreId] = useState('');
  const [filtreNom, setFiltreNom] = useState('');
  const [filtreChemin, setFiltreChemin] = useState('');

  const chargerVisages = async () => {
    try {
      const res = await apiFetch(`${serveurService.getApiUrl()}/visages`);
      const data = await res.json();
      setVisages(data);
    } catch (e) { console.error(e); }
  };

  useEffect(() => { chargerVisages(); }, []);

  const getUrlImage = (chemin: string) => {
    if (!chemin) return '';
    // Extraire uniquement le nom du fichier (ex: brad_pitt.jpg)
    const nomFichier = chemin.split('/').pop()?.split('\\').pop();
    // Enlever /api à la fin de l'URL du serveur si nécessaire
    const rootUrl = serveurService.getApiUrl().replace(/\/api$/, '');
    const isDjango = serveurService.getBackend() === 'django';
    // Construire le chemin propre
    return isDjango ? `${rootUrl}/media/visages/${nomFichier}` : `${rootUrl}/uploads/visages/${nomFichier}`;
  };

  const supprimerVisage = async (id: number) => {
    if(window.confirm('Supprimer ce visage effacera aussi son vecteur IA. Continuer ?')) {
      const suffix = serveurService.getBackend() === 'django' ? '/' : '';
      await apiFetch(`${serveurService.getApiUrl()}/visages/${id}${suffix}`, { method: 'DELETE' });
      chargerVisages();
    }
  };

  // 👉 Logique de filtrage en temps réel
  const visagesFiltres = visages.filter(v => {
    const cheminDB = v.chemin_image || v.cheminImage || '';
    const matchId = v.id.toString().includes(filtreId);
    const matchNom = v.nom.toLowerCase().includes(filtreNom.toLowerCase());
    const matchChemin = cheminDB.toLowerCase().includes(filtreChemin.toLowerCase());
    return matchId && matchNom && matchChemin;
  });

  return (
    <div className="crud-section">
      <div className="section-header" style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}>
        <h3>Base Biométrique (FAISS)</h3>
        <Link to="/admin/visages/nouveau" className="btn-submit" style={{ width: 'auto', margin: 0, textDecoration: 'none', display: 'inline-block' }}>➕ Ajouter Visage</Link>
      </div>

      {/* 👉 BARRE DE FILTRES */}
      <div className="filter-row">
        <div className="filter-group">
          <label>🔍 Recherche ID</label>
          <input type="text" placeholder="Ex: 5" value={filtreId} onChange={e => setFiltreId(e.target.value)} />
        </div>
        <div className="filter-group">
          <label>👤 Nom Complet</label>
          <input type="text" placeholder="Ex: Brad Pitt" value={filtreNom} onChange={e => setFiltreNom(e.target.value)} />
        </div>
        <div className="filter-group">
          <label>📁 Chemin / Fichier</label>
          <input type="text" placeholder="Ex: brad_pitt.jpg" value={filtreChemin} onChange={e => setFiltreChemin(e.target.value)} />
        </div>
      </div>

      <table className="admin-table">
        <thead>
          <tr><th>Photo</th><th>ID IA</th><th>Nom Complet</th><th>Chemin DB</th><th>Actions</th></tr>
        </thead>
        <tbody>
          {visagesFiltres.map(v => (
            <tr key={v.id}>
              <td>
                <img 
                  src={getUrlImage(v.chemin_image || v.cheminImage)} 
                  alt="Visage" 
                  className={`visage-thumbnail ${imageZoomee === v.id ? 'zoom' : ''}`}
                  onClick={() => setImageZoomee(imageZoomee === v.id ? null : v.id)}
                  style={{ width: '50px', height: '50px', borderRadius: '5px', cursor: 'pointer', objectFit: 'cover' }}
                />
              </td>
              <td>#{v.id}</td>
              <td>{v.nom}</td>
              <td style={{ fontSize: '12px', color: '#64748b' }}>{v.chemin_image || v.cheminImage}</td>
              <td>
                <button onClick={() => navigate(`/admin/visages/modifier/${v.id}`)} className="btn-action btn-edit">✏️ Modifier</button>
                <button className="btn-action btn-delete" onClick={() => supprimerVisage(v.id)}>🗑️ Supprimer</button>
              </td>
            </tr>
          ))}
          {visagesFiltres.length === 0 && (
            <tr><td colSpan={5} style={{textAlign: 'center', padding: '20px'}}>Aucun visage trouvé.</td></tr>
          )}
        </tbody>
      </table>
    </div>
  );
};

// FRONT/front/src/app/components/admin-visages/admin-visages.component.ts
import { Component, OnInit, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { RouterModule } from '@angular/router';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { FormsModule } from '@angular/forms'; // 👉 Import ajouté pour [(ngModel)]
import { ServeurService } from '../../services/serveur.service';
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-admin-visages',
  standalone: true,
  imports: [CommonModule, RouterModule, FormsModule],
  templateUrl: './admin-visages.component.html',
  styles: [`
    .visage-thumbnail { width: 50px; height: 50px; border-radius: 5px; cursor: pointer; object-fit: cover; transition: transform 0.3s; }
    .visage-thumbnail.zoom { transform: scale(4); z-index: 100; position: relative; border: 2px solid #3b82f6; }
  `]
})
export class AdminVisagesComponent implements OnInit {
  private http = inject(HttpClient);
  private serveurService = inject(ServeurService);
  private authService = inject(AuthService);
  
  visages: any[] = [];
  imageZoomee: number | null = null;

  // 👉 Variables de filtres
  filtreId: string = '';
  filtreNom: string = '';
  filtreChemin: string = '';

  ngOnInit() { this.chargerVisages(); }

  chargerVisages() {
    const headers = new HttpHeaders().set('Authorization', `Bearer ${this.authService.getToken()}`);
    this.http.get<any[]>(`${this.serveurService.getApiUrl()}/visages`, { headers }).subscribe(data => this.visages = data);
  }

  getUrlImage(chemin: string): string {
    if (!chemin) return '';
    const nomFichier = chemin.split('/').pop()?.split('\\').pop();
    const rootUrl = this.serveurService.getApiUrl().replace(/\/api$/, '');
    const isDjango = this.serveurService.getBackend() === 'django';
    return isDjango ? `${rootUrl}/media/visages/${nomFichier}` : `${rootUrl}/uploads/visages/${nomFichier}`;
  }

  supprimerVisage(id: number) {
    if(confirm('Supprimer ce visage effacera aussi son vecteur IA. Continuer ?')) {
      const headers = new HttpHeaders().set('Authorization', `Bearer ${this.authService.getToken()}`);
      const suffix = this.serveurService.getBackend() === 'django' ? '/' : '';
      this.http.delete(`${this.serveurService.getApiUrl()}/visages/${id}${suffix}`, { headers }).subscribe(() => {
        this.chargerVisages();
      });
    }
  }

  // 👉 Le Getter qui filtre les données pour le HTML
  get visagesFiltres() {
    return this.visages.filter(v => {
      const cheminDB = v.chemin_image || v.cheminImage || '';
      const matchId = v.id.toString().includes(this.filtreId);
      const matchNom = v.nom.toLowerCase().includes(this.filtreNom.toLowerCase());
      const matchChemin = cheminDB.toLowerCase().includes(this.filtreChemin.toLowerCase());
      return matchId && matchNom && matchChemin;
    });
  }
}
<div class="crud-section">
  <div class="section-header" style="display: flex; justify-content: space-between; align-items: center;">
    <h3>Base Biométrique (FAISS)</h3>
    <button routerLink="/admin/visages/nouveau" class="btn-submit" style="width: auto; margin:0;">➕ Ajouter Visage</button>
  </div>

  <div class="filter-row">
    <div class="filter-group">
      <label>🔍 Recherche ID</label>
      <input type="text" placeholder="Ex: 5" [(ngModel)]="filtreId">
    </div>
    <div class="filter-group">
      <label>👤 Nom Complet</label>
      <input type="text" placeholder="Ex: Brad Pitt" [(ngModel)]="filtreNom">
    </div>
    <div class="filter-group">
      <label>📁 Chemin / Fichier</label>
      <input type="text" placeholder="Ex: brad_pitt.jpg" [(ngModel)]="filtreChemin">
    </div>
  </div>

  <table class="admin-table">
    <thead>
      <tr><th>Photo</th> <th>ID IA</th> <th>Nom Complet</th> <th>Chemin DB</th> <th>Actions</th></tr>
    </thead>
    <tbody>
      <tr *ngFor="let v of visagesFiltres">
        <td>
          <img [src]="getUrlImage(v.chemin_image || v.cheminImage)" alt="Visage" 
               class="visage-thumbnail" 
               [class.zoom]="imageZoomee === v.id" 
               (click)="imageZoomee = imageZoomee === v.id ? null : v.id">
        </td>
        <td>#{{ v.id }}</td>
        <td>{{ v.nom }}</td>
        <td style="font-size: 12px; color: #64748b;">{{ v.chemin_image || v.cheminImage }}</td>
        <td>
          <button routerLink="/admin/visages/modifier/{{v.id}}" class="btn-action btn-edit">✏️ Modifier</button>
          <button class="btn-action btn-delete" (click)="supprimerVisage(v.id)">🗑️ Supprimer</button>
        </td>
      </tr>
      <tr *ngIf="visagesFiltres.length === 0">
        <td colspan="5" style="text-align: center; padding: 20px;">Aucun visage trouvé.</td>
      </tr>
    </tbody>
  </table>
</div>
