// FRONTREACT/front-react/src/components/chat/Chat.tsx
import { useState } from 'react';
import './Chat.css';
import type { Message } from '../../models/message';
import { chatService } from '../../services/chat.service';

export const Chat: React.FC = () => {
  const [messages, setMessages] = useState<Message[]>([]);
  const [currentPrompt, setCurrentPrompt] = useState('');
  const [selectedFile, setSelectedFile] = useState<File | null>(null);
  const [isLoading, setIsLoading] = useState(false);

  const onFileSelected = (event: React.ChangeEvent<HTMLInputElement>) => {
    const file = event.target.files?.[0];
    if (file) setSelectedFile(file);
  };

  const removeFile = () => setSelectedFile(null);

  const sendMessage = async () => {
    if (!currentPrompt.trim() && !selectedFile) return;

    setIsLoading(true);

    const userMessage: Message = {
      sender: 'user',
      text: currentPrompt,
      fileName: selectedFile?.name
    };
    setMessages(prev => [...prev, userMessage]);

    const request: any = { prompt: currentPrompt };
    if (selectedFile) {
      request.file_name = selectedFile.name;
      request.file_base64 = await chatService.convertFileToBase64(selectedFile);
    }

    setCurrentPrompt('');
    setSelectedFile(null);

    try {
      const response = await chatService.sendMessage(request);
      let downloadLink: string | undefined = undefined;

      if (response.output_file_base64 && response.output_file_name) {
        downloadLink = chatService.createDownloadUrl(response.output_file_base64);
      }

      setMessages(prev => [...prev, {
        sender: 'ia',
        text: response.text,
        fileName: response.output_file_name,
        downloadUrl: downloadLink
      }]);
    } catch (error: any) {
      const errorTexte = error.message || JSON.stringify(error);
      let messageErreur = "";

      if (errorTexte.includes('503') || errorTexte.includes('high demand') || errorTexte.includes('UNAVAILABLE')) {
        messageErreur = "L'IA de Google est surchargée. Veuillez réessayer dans quelques minutes ! ⏳";
      } else if (errorTexte.includes('429') || errorTexte.includes('quota')) {
        messageErreur = "Le quota gratuit de l'IA est atteint pour aujourd'hui. 🛑";
      } else {
        messageErreur = "Erreur de communication avec l'IA. ❌";
      }

      setMessages(prev => [...prev, { sender: 'ia', text: messageErreur }]);
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <div className="chat-container">
      <div className="messages-area">
        {messages.map((msg, index) => (
          <div key={index} className={`message-bubble ${msg.sender}`}>
            <strong>{msg.sender === 'user' ? 'Vous' : 'IA Bureautique'}</strong>
            <p>{msg.text}</p>
            
            {msg.sender === 'user' && msg.fileName && (
              <div className="file-attachment">📎 {msg.fileName}</div>
            )}

            {msg.sender === 'ia' && msg.downloadUrl && (
              <a href={msg.downloadUrl} download={msg.fileName} className="download-btn">
                ⬇️ Télécharger {msg.fileName}
              </a>
            )}
          </div>
        ))}
        
        {isLoading && (
          <div className="message-bubble ia loading">
            <em>L'IA réfléchit (et LibreOffice mouline)...</em>
          </div>
        )}
      </div>

      <div className="input-area">
        {selectedFile && (
          <div className="selected-file-badge">
            📎 {selectedFile.name}
            <button onClick={removeFile}>❌</button>
          </div>
        )}

        <div className="controls">
          <input type="file" id="fileUpload" onChange={onFileSelected} hidden />
          <label htmlFor="fileUpload" className="file-btn">📎 Pièce jointe</label>

          <textarea 
            value={currentPrompt}
            onChange={(e) => setCurrentPrompt(e.target.value)}
            placeholder="Demandez-moi de modifier un fichier, de créer un rapport..."
            rows={2}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && !e.shiftKey) {
                e.preventDefault();
                sendMessage();
              }
            }}
          />

          <button className="send-btn" onClick={sendMessage} disabled={isLoading}>
            Envoyer
          </button>
        </div>
      </div>
    </div>
  );
};

// FRONT/front/src/app/components/chat/chat.component.ts
import { CommonModule } from '@angular/common';
import { Component, inject } from '@angular/core';
import { ChatRequest } from '../../models/chat-request';
import { ChatService } from '../../services/chat.service';
import { FormsModule } from '@angular/forms';
import { Message } from '../../models/message';
import { HttpErrorResponse } from '@angular/common/http';

@Component({
  selector: 'app-chat',
  imports: [CommonModule, FormsModule],
  templateUrl: './chat.component.html',
  styleUrl: './chat.component.css'
})
export class ChatComponent {
  private chatService = inject(ChatService);

  messages: Message[] = [];
  currentPrompt: string = '';
  selectedFile: File | null = null;
  isLoading: boolean = false;

  onFileSelected(event: any) {
    const file: File = event.target.files[0];
    if (file) {
      this.selectedFile = file;
    }
  }

  removeFile() {
    this.selectedFile = null;
  }

  async sendMessage() {
    if (!this.currentPrompt.trim() && !this.selectedFile) return;

    this.isLoading = true;

    this.messages.push({
      sender: 'user',
      text: this.currentPrompt,
      fileName: this.selectedFile?.name
    });

    const request: ChatRequest = { prompt: this.currentPrompt };
    
    if (this.selectedFile) {
      request.file_name = this.selectedFile.name;
      request.file_base64 = await this.chatService.convertFileToBase64(this.selectedFile);
    }

    this.currentPrompt = '';
    this.selectedFile = null;

    this.chatService.sendMessage(request).subscribe({
      next: (response) => {
        let downloadLink = undefined;

        if (response.output_file_base64 && response.output_file_name) {
          downloadLink = this.chatService.createDownloadUrl(
            response.output_file_base64, 
            response.output_file_name
          );
        }

        this.messages.push({
          sender: 'ia',
          text: response.text,
          fileName: response.output_file_name,
          downloadUrl: downloadLink
        });
        
        this.isLoading = false;
      },
      error: (err: HttpErrorResponse) => {
        const errorTexte = JSON.stringify(err);
        let messageErreur = "";

        if (errorTexte.includes('503') || errorTexte.includes('high demand') || errorTexte.includes('UNAVAILABLE')) {
          messageErreur = "L'IA de Google est surchargée. Veuillez réessayer dans quelques minutes ! ⏳";
        } else if (errorTexte.includes('429') || errorTexte.includes('quota')) {
          messageErreur = "Le quota gratuit de l'IA est atteint pour aujourd'hui. 🛑";
        } else {
          messageErreur = "Erreur de communication avec l'IA. ❌";
        }
        
        this.messages.push({
          sender: 'ia',
          text: messageErreur
        });

        this.isLoading = false;
      }
    });
  }
}
<div class="chat-container">
  
  <div class="messages-area">
    @for (msg of messages; track $index) {
      <div class="message-bubble" [ngClass]="msg.sender">
        <strong>{{ msg.sender === 'user' ? 'Vous' : 'IA Bureautique' }}</strong>
        <p>{{ msg.text }}</p>
        
        @if (msg.sender === 'user' && msg.fileName) {
          <div class="file-attachment">📎 {{ msg.fileName }}</div>
        }

        @if (msg.sender === 'ia' && msg.downloadUrl) {
          <a [href]="msg.downloadUrl" [download]="msg.fileName" class="download-btn">⬇️ Télécharger {{ msg.fileName }}</a>
        }
      </div>
    }
    
    @if (isLoading) {
      <div class="message-bubble ia loading">
        <em>L'IA réfléchit (et LibreOffice mouline)...</em>
      </div>
    }
  </div>

  <div class="input-area">
    @if (selectedFile) {
      <div class="selected-file-badge">
        📎 {{ selectedFile.name }}
        <button (click)="removeFile()">❌</button>
      </div>
    }

    <div class="controls">
      <input type="file" id="fileUpload" (change)="onFileSelected($event)" hidden>
      <label for="fileUpload" class="file-btn">📎 Pièce jointe</label>

      <textarea 
        [(ngModel)]="currentPrompt" 
        placeholder="Demandez-moi de modifier un fichier, de créer un rapport..."
        rows="2"
        (keyup.enter)="sendMessage()">
      </textarea>

      <button class="send-btn" (click)="sendMessage()" [disabled]="isLoading">Envoyer</button>
    </div>
  </div>
</div>
