// FRONTREACT/front-react/src/components/admin-visage-form/AdminVisageForm.tsx
import React, { useState, useEffect } from 'react';
import { useNavigate, useParams } from 'react-router-dom';
import { serveurService } from '../../services/serveur.service';
import { authService } from '../../services/auth.service';
import { apiFetch } from '../../services/jwt.interceptor'; // 👉 Important pour les requêtes JSON sécurisées
import './AdminVisageForm.css';

export const AdminVisageForm: React.FC = () => {
  const navigate = useNavigate();
  const { id } = useParams();
  const isEdit = !!id;

  const [nom, setNom] = useState('');
  const [chemin, setChemin] = useState(''); // 👉 Nouveau champ
  const [fichier, setFichier] = useState<File | null>(null);

  // 👉 Récupération des données si on est en mode Modification
  useEffect(() => {
    if (isEdit) {
      apiFetch(`${serveurService.getApiUrl()}/visages`)
        .then(res => res.json())
        .then(data => {
          const visageActuel = data.find((x: any) => x.id.toString() === id);
          if (visageActuel) {
            setNom(visageActuel.nom);
            setChemin(visageActuel.chemin_image || visageActuel.cheminImage);
          }
        });
    }
  }, [isEdit, id]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    const isDjango = serveurService.getBackend() === 'django';
    
    try {
      if (isEdit) {
        // 👉 REQUÊTE DE MODIFICATION (PUT)
        const endpoint = isDjango ? `/visages/${id}/` : `/visages/${id}`;
        await apiFetch(`${serveurService.getApiUrl()}${endpoint}`, {
          method: 'PUT',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ nom, chemin_image: chemin })
        });
        alert('Modifications sauvegardées avec succès !');
        navigate('/admin/visages');

      } else {
        // 👉 REQUÊTE D'AJOUT (POST MULTIPART avec Token manuel)
        if (!fichier || !nom) return;
        const formData = new FormData();
        formData.append('nom', nom);
        formData.append('image', fichier);

        const endpoint = isDjango ? '/visages/' : '/visages/ajouter';
        
        // On utilise fetch classique ici car formData gère son propre Content-Type
        const res = await fetch(`${serveurService.getApiUrl()}${endpoint}`, {
          method: 'POST',
          headers: { 'Authorization': `Bearer ${authService.getToken()}` }, // Fix du 401
          body: formData 
        });
        
        if (!res.ok) throw new Error("Erreur serveur");
        alert('Visage encodé et ajouté à la base de données IA !');
        navigate('/admin/visages');
      }
    } catch (err) {
      alert('Erreur technique lors de la transaction.');
    }
  };

  return (
    <div className="login-box" style={{ margin: '2rem auto' }}>
      <h2>{isEdit ? 'Modifier' : 'Ajouter'} un Visage</h2>
      <form onSubmit={handleSubmit}>
        <div className="form-group">
          <label>Nom Complet</label>
          <input type="text" value={nom} onChange={e => setNom(e.target.value)} required />
        </div>
        
        {isEdit ? (
          <div className="form-group">
            <label>Chemin de l'image (Base de données)</label>
            <input type="text" value={chemin} onChange={e => setChemin(e.target.value)} required />
          </div>
        ) : (
          <div className="form-group">
            <label>Photo du visage</label>
            <input type="file" onChange={e => setFichier(e.target.files ? e.target.files[0] : null)} accept="image/png, image/jpeg" required />
          </div>
        )}
        
        <button type="submit" className="btn-submit">
          {isEdit ? 'Sauvegarder les modifications' : 'Sauvegarder et Synchroniser IA'}
        </button>
      </form>
    </div>
  );
};

// FRONT/front/src/app/components/admin-visage-form/admin-visage-form.component.ts
import { Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpHeaders } from '@angular/common/http';
import { ActivatedRoute, Router } from '@angular/router';
import { ServeurService } from '../../services/serveur.service';
import { AuthService } from '../../services/auth.service'; // 👉 Nouvel import

@Component({
  selector: 'app-admin-visage-form',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './admin-visage-form.component.html',
  styleUrls: ['./admin-visage-form.component.css']
})
export class AdminVisageFormComponent implements OnInit {
  private http = inject(HttpClient);
  private serveurService = inject(ServeurService);
  private authService = inject(AuthService);
  private router = inject(Router);
  private route = inject(ActivatedRoute);

  nom: string = '';
  chemin: string = ''; // 👉 Nouveau champ
  fichierSelectionne: File | null = null;
  isEdit = false;
  visageId: string | null = null;

  ngOnInit() {
    this.visageId = this.route.snapshot.paramMap.get('id');
    if (this.visageId) {
      this.isEdit = true;
      const headers = new HttpHeaders().set('Authorization', `Bearer ${this.authService.getToken()}`);
      
      this.http.get<any[]>(`${this.serveurService.getApiUrl()}/visages`, { headers }).subscribe(data => {
        const visageActuel = data.find(x => x.id.toString() === this.visageId);
        if (visageActuel) {
          this.nom = visageActuel.nom;
          this.chemin = visageActuel.chemin_image || visageActuel.cheminImage;
        }
      });
    }
  }

  onFileSelected(event: any) {
    this.fichierSelectionne = event.target.files[0];
  }

  onSubmit() {
    const isDjango = this.serveurService.getBackend() === 'django';
    const headers = new HttpHeaders().set('Authorization', `Bearer ${this.authService.getToken()}`);

    if (this.isEdit) {
      // 👉 REQUÊTE DE MODIFICATION (PUT)
      const url = `${this.serveurService.getApiUrl()}/visages/${this.visageId}${isDjango ? '/' : ''}`;
      
      this.http.put(url, { nom: this.nom, chemin_image: this.chemin }, { headers }).subscribe({
        next: () => {
          alert('Modifications sauvegardées avec succès !');
          this.router.navigate(['/admin/visages']);
        },
        error: (err) => alert('Erreur : ' + err.message)
      });

    } else {
      // 👉 REQUÊTE D'AJOUT (POST MULTIPART)
      if (!this.fichierSelectionne || !this.nom) return;

      const formData = new FormData();
      formData.append('nom', this.nom);
      formData.append('image', this.fichierSelectionne);

      // On enlève le /api redondant qui causait l'erreur 404
      const url = `${this.serveurService.getApiUrl()}${isDjango ? '/visages/' : '/visages/ajouter'}`;

      this.http.post(url, formData, { headers }).subscribe({
        next: () => {
          alert('Visage encodé et ajouté à la base de données IA !');
          this.router.navigate(['/admin/visages']);
        },
        error: (err) => alert('Erreur : ' + err.message)
      });
    }
  }
}
<div class="login-box" style="margin: 2rem auto;">
  <h2>{{ isEdit ? 'Modifier' : 'Ajouter' }} un Visage</h2>
  <form (ngSubmit)="onSubmit()">
    
    <div class="form-group">
      <label>Nom Complet</label>
      <input type="text" [(ngModel)]="nom" name="nom" required>
    </div>
    
    <div class="form-group" *ngIf="isEdit">
      <label>Chemin de l'image (Base de données)</label>
      <input type="text" [(ngModel)]="chemin" name="chemin" required>
    </div>
    
    <div class="form-group" *ngIf="!isEdit">
      <label>Photo du visage</label>
      <input type="file" (change)="onFileSelected($event)" accept="image/png, image/jpeg" required>
    </div>
    
    <button type="submit" class="btn-submit">
      {{ isEdit ? 'Sauvegarder les modifications' : 'Sauvegarder et Synchroniser IA' }}
    </button>
  </form>
</div>
