// FRONT/front/src/app/components/login/login.component.ts
import { ChangeDetectorRef, Component, inject, OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterModule } from '@angular/router';
import { AuthService } from '../../services/auth.service';
import { ChatService } from '../../services/chat.service'; 

@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule, RouterModule],
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.css']
})
export class LoginComponent implements OnInit {
  public authService = inject(AuthService);
  public chatService = inject(ChatService);
  private router = inject(Router);
  public route = inject(ActivatedRoute); 
  private cdr = inject(ChangeDetectorRef);

  isLoginMode = true; 
  hidePassword = true;
  
  formData = {
    email: '',
    motDePasse: ''
  };

  messageErreur = '';

  ngOnInit() {
    this.route.queryParams.subscribe(params => {
      if (params['token']) {
        const token = params['token'];
        const id = params['id'] || '0';
        const role = params['role'] || 'ROLE_USER';
        const email = params['email'] || 'social_user@ia.com';
        const backend = params['backend']; // 👉 On récupère l'identité du serveur

        this.authService.sauvegarderSession(token, role, email, id);

        // 👉 Si le serveur a déclaré son identité, on l'applique immédiatement
        if (backend === 'spring' || backend === 'django') {
          this.chatService.setBackend(backend);
        }

        this.router.navigate(['/chat']);
      }
    });
  }

  togglePasswordVisibility() {
    this.hidePassword = !this.hidePassword;
  }

  onSubmit() {
    this.messageErreur = '';

    if (this.isLoginMode) {
      this.authService.login(this.formData.email, this.formData.motDePasse).subscribe({
        next: () => {
          this.router.navigate(['/chat']);
        },
        error: () => {
          this.messageErreur = "Identifiants incorrects.";
          this.cdr.detectChanges(); 
        }
      });
    }
  }

  connexionSociale(fournisseur: 'google' | 'github') {
    const baseUrl = this.authService.getBaseUrl(); 
    const backend = this.chatService.getCurrentBackend();

    if (backend === 'django') {
      window.location.href = `${baseUrl}/auth/${fournisseur}/login/?frontend=angular`;
    } else {
      window.location.href = `${baseUrl}/auth/init-social?fournisseur=${fournisseur}&frontend=angular`;
    }
  }
}
<div class="login-container">
  <div class="login-box">
    
    <h2>Connexion à l'IA</h2>

    <div *ngIf="messageErreur" class="alert error">{{ messageErreur }}</div>

    <form (ngSubmit)="onSubmit()">
      
      <div class="form-group">
        <label for="email">Adresse Email</label>
        <input type="email" id="email" name="email" [(ngModel)]="formData.email" placeholder="utilisateur@exemple.com" required>
      </div>

      <div class="form-group">
        <label for="password">Mot de passe</label>
        <div class="password-wrapper">
          <input 
            [type]="hidePassword ? 'password' : 'text'" 
            id="password" 
            name="password" 
            [(ngModel)]="formData.motDePasse" 
            placeholder="••••••••" 
            required
          >
          <button type="button" class="btn-eye" (click)="togglePasswordVisibility()">
            {{ hidePassword ? '👁️' : '🙈' }}
          </button>
        </div>
      </div>

      <button type="submit" class="btn-submit">Se Connecter</button>

      <div class="toggle-mode">
        Pas encore inscrit ? <a routerLink="/inscription">Créer un compte ici</a>
      </div>
    </form>

    <div class="divider">
      <span>OU</span>
    </div>

    <div class="social-login">
      <div class="social-buttons">
        <button type="button" class="btn-social google" (click)="connexionSociale('google')">
          <img src="https://upload.wikimedia.org/wikipedia/commons/c/c1/Google_%22G%22_logo.svg" alt="Google">
          Google
        </button>
        <button type="button" class="btn-social github" (click)="connexionSociale('github')">
          <img src="https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg" alt="GitHub">
          GitHub
        </button>
      </div>
    </div>

  </div>
</div>

// FRONTREACT/front-react/src/components/login/Login.tsx
import { useState, useEffect } from 'react';
import { useNavigate, useSearchParams, Link } from 'react-router-dom';
import { AuthService } from '../../services/auth.service';
import { chatService } from '../../services/chat.service';
import './Login.css';

export const LoginComponent = () => {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const [hidePassword, setHidePassword] = useState(true);
  const [messageErreur, setMessageErreur] = useState('');
  
  const [formData, setFormData] = useState({
    email: '',
    motDePasse: ''
  });

  useEffect(() => {
    const token = searchParams.get('token');
    if (token) {
      const id = searchParams.get('id') || '0';
      const role = searchParams.get('role') || 'ROLE_USER';
      const email = searchParams.get('email') || 'social_user@ia.com';
      const backend = searchParams.get('backend'); // 👉 On récupère l'identité du serveur

      AuthService.sauvegarderSession(token, role, email, id);
      
      // 👉 Si le serveur a déclaré son identité, on l'applique immédiatement
      if (backend === 'spring' || backend === 'django') {
        chatService.setBackend(backend as any);
      }

      navigate('/chat');
    }
  }, [searchParams, navigate]);
  
  const onSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    setMessageErreur('');

    AuthService.login(formData.email, formData.motDePasse).subscribe({
      next: () => {
        navigate('/chat');
      },
      error: () => {
        setMessageErreur("Identifiants incorrects.");
      }
    });
  };

  const connexionSociale = (fournisseur: 'google' | 'github') => {
    const baseUrl = AuthService.getBaseUrl(); 
    const backend = chatService.getCurrentBackend();

    if (backend === 'django') {
      window.location.href = `${baseUrl}/auth/${fournisseur}/login/?frontend=react`;
    } else {
      window.location.href = `${baseUrl}/auth/init-social?fournisseur=${fournisseur}&frontend=react`;
    }
  };

  return (
    <div className="login-container">
      <div className="login-box">
        <h2>Connexion à l'IA</h2>
        {messageErreur && <div className="alert error">{messageErreur}</div>}

        <form onSubmit={onSubmit}>
          <div className="form-group">
            <label>Adresse Email</label>
            <input 
              type="email" 
              value={formData.email} 
              onChange={(e) => setFormData({...formData, email: e.target.value})} 
              placeholder="utilisateur@exemple.com" 
              required 
            />
          </div>

          <div className="form-group">
            <label>Mot de passe</label>
            <div className="password-wrapper">
              <input 
                type={hidePassword ? 'password' : 'text'} 
                value={formData.motDePasse} 
                onChange={(e) => setFormData({...formData, motDePasse: e.target.value})} 
                placeholder="••••••••" 
                required 
              />
              <button type="button" className="btn-eye" onClick={() => setHidePassword(!hidePassword)}>
                {hidePassword ? '👁️' : '🙈'}
              </button>
            </div>
          </div>

          <button type="submit" className="btn-submit">Se Connecter</button>

          {/* 👉 LIEN RÉACTIVÉ VERS L'INSCRIPTION */}
          <div className="toggle-mode">
            Pas encore inscrit ? <Link to="/inscription">Créer un compte ici</Link>
          </div>
        </form>

        <div className="divider"><span>OU</span></div>

        <div className="social-login">
          <div className="social-buttons">
            <button type="button" className="btn-social google" onClick={() => connexionSociale('google')}>
              <img src="https://upload.wikimedia.org/wikipedia/commons/c/c1/Google_%22G%22_logo.svg" alt="Google" />
              Google
            </button>
            <button type="button" className="btn-social github" onClick={() => connexionSociale('github')}>
              <img src="https://upload.wikimedia.org/wikipedia/commons/9/91/Octicons-mark-github.svg" alt="GitHub" />
              GitHub
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
