// FRONTREACT/front-react/src/components/admin-dashboard/AdminDashboard.tsx
import React from 'react';
import { NavLink, Outlet, useNavigate } from 'react-router-dom';
import { authService } from '../../services/auth.service';
import './AdminDashboard.css';

export const AdminDashboard: React.FC = () => {
  const navigate = useNavigate();

  const deconnexion = () => {
    authService.logout();
    navigate('/login');
  };

  return (
    <div className="admin-container">
      <aside className="admin-sidebar">
        <div className="sidebar-header">
          <h2>🛡️ Espace Admin</h2>
        </div>
        <nav className="sidebar-nav">
          <NavLink to="/admin/utilisateurs" className={({isActive}) => isActive ? "nav-item actif" : "nav-item"}>
            👥 Liste Utilisateurs
          </NavLink>
          <NavLink to="/admin/visages" className={({isActive}) => isActive ? "nav-item actif" : "nav-item"}>
            👤 Base Biométrique (IA)
          </NavLink>
          {/* 👉 LE NOUVEAU BOUTON CHAT */}
          <NavLink to="/chat" className={({isActive}) => isActive ? "nav-item actif" : "nav-item"}>
            💬 Accéder au Chat
          </NavLink>
        </nav>
        <div className="sidebar-footer">
          <button className="btn-deconnexion" onClick={deconnexion}>Déconnexion</button>
        </div>
      </aside>

      <main className="admin-content">
        <Outlet /> {/* Les composants Utilisateurs ou Visages s'injectent ici */}
      </main>
    </div>
  );
};

// FRONT/front/src/app/components/admin-dashboard/admin-dashboard.component.ts
import { Component, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import { Router, RouterModule, RouterOutlet } from '@angular/router'; 
import { AuthService } from '../../services/auth.service';

@Component({
  selector: 'app-admin-dashboard',
  standalone: true,
  imports: [CommonModule, RouterModule, RouterOutlet], 
  templateUrl: './admin-dashboard.component.html',
  styleUrls: ['./admin-dashboard.component.css']
})
export class AdminDashboardComponent {
  private authService = inject(AuthService);
  private router = inject(Router);

  deconnexion() {
    this.authService.logout();
    this.router.navigate(['/login']);
  }
}
<div class="admin-container">
  <aside class="admin-sidebar">
    <div class="sidebar-header">
      <h2>🛡️ Espace Admin</h2>
    </div>
    <nav class="sidebar-nav">      
      <a routerLink="/admin/utilisateurs" routerLinkActive="actif" class="nav-item">👥 Liste Utilisateurs</a>
      <a routerLink="/admin/visages" routerLinkActive="actif" class="nav-item">👤 Base Biométrique (IA)</a>
      <a routerLink="/chat" routerLinkActive="actif" class="nav-item">💬 Accéder au Chat</a>
    </nav>
    <div class="sidebar-footer">
      <button class="btn-deconnexion" (click)="deconnexion()">Déconnexion</button>
    </div>
  </aside>
  <main class="admin-content">
    <router-outlet></router-outlet> </main>
</div>
